apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employeecrud-aws-eks
  name: employeecrud-aws-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeecrud-aws-eks
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: employeecrud-aws-eks
    spec:
      containers:
        name: employeecrud-aws-eks
      - image: 851725279940.dkr.ecr.us-east-2.amazonaws.com/employeecrud-aws-eks:latest
        imagePullPolicy: IfNotPresent
        ports:
        -  containerPort: 8000
        resources:
          requests: 
            cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employeecrud-aws-eks
  name: employeecrud-aws-eks
spec:
  ports:
  -  protocol: TCP
     port: 80
     targetPort: 8000
  selector:
    app: employeecrud-aws-eks
  type: LoadBalancer