CREATE DATABASE IF NOT EXISTS employee_dir;

USE employee_dir;

DROP TABLE IF EXISTS employee;

CREATE TABLE employee(
  id INTEGER NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) DEFAULT NULL,
  last_name VARCHAR(45) DEFAULT NULL,
  age INTEGER,
  salary INTEGER,
  department VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (id)
);